# Generated by Django 3.2.25 on 2025-07-12 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='swaprequest',
            old_name='to_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='swaprequest',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='offered_skill',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='wanted_skill',
        ),
        migrations.AddField(
            model_name='feedback',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='is_offered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skill_offered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='core.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skill_requested',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='core.skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
